[package]
name = "instructor-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
instructor-derive-internals = { path = "../instructor-derive-internals" }
syn = "2.0.60"