[package]
name = "instructor"
version = "0.1.0"
edition = "2021"

[features]
derive = ["instructor-derive"]

[dependencies]
bytes = "1"
instructor-derive = { path = "../instructor-derive", optional = true }

[dev-dependencies]
bitflags = "2.5.0"